"""add duration to plans

Revision ID: d14b847ddcd9
Revises: 60fa10c8da8a
Create Date: 2026-08-29 19:11:13.261138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14b847ddcd9'
down_revision: Union[str, Sequence[str], None] = '60fa10c8da8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'duration_minutes')
    # ### end Alembic commands ###
